### ISSUE TITLE
Hass.io ngrok Client

### ISSUE THREAD

**Issue by pssc** [ThePicklenat0r/hassio-addons#20]
Hi Dylan,

I am I user of your ngrock addon it needs to be updated to work by mid January (client version issues.)  I am happy to do this and take over and publish the addon(I maintain a few already)  as you don't support this any more.  Are you happy for me do do so or are you going to update the addon?

Thanks

Phill.

**Comment by zlucio** [comment]
Dear Dylan
I have been using your ngrok integration in HA for a long time, but unfortunately since January 15, 2024 ngrok asks to update the client. Consider updating your integration so you can reuse it after that date. Thanks for your time.

**Comment by o0larrylurex0o** [comment]
> Hi Dylan,
> 
> I am I user of your ngrock addon it needs to be updated to work by mid January (client version issues.) I am happy to do this and take over and publish the addon(I maintain a few already) as you don't support this any more. Are you happy for me do do so or are you going to update the addon?
> 
> Thanks
> 
> Phill.

Hello @pssc , I would be very glad if you could fork this Add as I am also using it quite a lot, and I have no skills to do such a thing !!!
thx a lot

**Comment by dy1io** [comment]
Hey all, as is posted on the readme for the ngrok add-on, I've deprecated this particular add-on and have no plans to continue working on it. I've not used ngrok in a few years myself and if they're completely redoing their client it is likely that the add-on would need to be completely re-done as well. If someone else would like to take the add-on and update it to the current state they can fork it and update it. I kept the add-on on the page because I know many people were still using it, but tried to make it clear that it would not be getting any more updates.

I'm currently using other solutions such as SSH tunnels using the Tunnels add-on or Cloudflare tunnels using the Cloudflare add-on. Both accomplish a similar goal, are still working, and if any bugs are found in either I'd be happy to fix them. The official Nabu Casa remote access now offers custom domain support as well, and should be considered as an option as well.

I'll be closing this issue as I do not plan on updating the add-on.

**Comment by pssc** [comment]
@dy1io thanks @dy1io yes well I use this in HA for other things TM not HA itself where Cloudflare and SSH are not appropriate. I guess up to this point it just worked (tm),  but anyway thank you for your work and providing clarity.

**Comment by pssc** [comment]
@zlucio @o0larrylurex0o there is now a forked repo that has an addon that can be installed at tested in parallel  ```https://github.com/pssc/ha-addon-ngrok```
This has the updated client that will work post 15 Jan.
Any feedback welcome. You should be able to copy paste your config using the yaml editor option and then stop/start old and new
